# ===============================
# = Spring configurations
# ===============================
spring:
  name: local
  # = HTTP requests configurations ##############################
  servlet:
    multipart:
      location: /tmp
  datasource:
    url:      ${env.SPRING_DATASOURCE_URL}
    username: ${env.SPRING_DATASOURCE_USERNAME}
    password: ${env.SPRING_DATASOURCE_PASSWORD}
server:
  port: 8081

docker:
  host: tcp://localhost:2375
  tls-verify: false
  cert-path: /home/user/.docker
